### ISSUE TITLE
Testing through HTTP API

### ISSUE THREAD

**Issue by plcharriere** [42Taskmaster/taskmaster#6]
We want to test our HTTP API with e2e tests using [Artillery](https://artillery.io).

What we want to test : 
- Check programs' statuses
- Start programs
- Stop programs
- Restart programs
- Get the current configuration
- Load a new configuration
- Shutdown the daemon

We will test these endpoints : 
- `GET /status` to get program statuses
- `POST /start` to start a program
- `POST /stop` top stop a program
- `POST /restart` top restart a program
- `GET /configuration` to get the current configuration 
- `PUT /configuration` to load a new configuration
- `DELETE /shutdown` to shutdown the daemon

Using Artillery, we will write multiple scenarios with multiple cases to check that the API is working as expected.

**Comment by Devessier** [comment]
We won't be using Artillery as it's designed to stress test API, when we just want to ensure correct responses.
Instead we will use [Strest](https://github.com/eykrehbein/strest).
